version = 1

[[steps]]
[steps.shell]
script = '''
echo "Configuring system parameters..."

sudo rm -f /etc/motd

sudo sed -i 's/^\(GRUB_CMDLINE_LINUX=\).*/\1"elevator=deadline systemd.unified_cgroup_hierarchy=1 cgroup_enable=memory swapaccount=1 cgroup.memory=nokmem random.trust_cpu=on"/' /etc/default/grub
sudo update-grub2

if [[ -r /etc/sysctl.conf ]]; then

    if ! grep -q unprivileged_userns_clone /etc/sysctl.conf; then
        sudo tee -a /etc/sysctl.conf > /dev/null <<'EOT'
# allow unprivileged user namespaces
kernel.unprivileged_userns_clone=1
EOT
    fi

    if ! grep -q ip_unprivileged_port_start /etc/sysctl.conf; then
        sudo tee -a /etc/sysctl.conf > /dev/null <<'EOT'
# allow lower unprivileged port bind
net.ipv4.ip_unprivileged_port_start=80
EOT
    fi

elif [[ -d /etc/sysctl.d/ ]]; then
    if ! grep -q unprivileged_userns_clone /etc/sysctl.d/*; then
        sudo tee -a /etc/sysctl.d/80_userns.conf > /dev/null <<'EOT'
# allow unprivileged user namespaces
kernel.unprivileged_userns_clone=1
EOT
    fi
    if ! grep -q ip_unprivileged_port_start /etc/sysctl.d/*; then
        sudo tee -a /etc/sysctl.d/80_lowport.conf > /dev/null <<'EOT'
# allow lower unprivileged port bind
net.ipv4.ip_unprivileged_port_start=80
EOT
    fi
fi

sudo mkdir -p /etc/modprobe.d
echo "options overlay permit_mounts_in_userns=1 metacopy=off redirect_dir=off" | sudo tee /etc/modprobe.d/overlay.conf

if [[ -d /etc/systemd/system ]]; then
    sudo mkdir -p /etc/systemd/system/user@.service.d
    echo -e "[Service]\\nDelegate=cpu cpuset io memory pids" | sudo tee /etc/systemd/system/user@.service.d/delegate.conf
fi

sudo touch /etc/subuid
sudo touch /etc/subgid
if ! grep --quiet "$USER" /etc/subuid; then
  sudo usermod --add-subuids 200000-265535 "$USER"
fi
if ! grep --quiet "$USER" /etc/subgid; then
  sudo usermod --add-subgids 200000-265535 "$USER"
fi

sudo loginctl enable-linger "$USER" &>/dev/null || true
sudo usermod -a -G systemd-journal "$USER" &>/dev/null || true
'''
