version = 1

[env]
VERBOSE = "false"

[[steps]]
[steps.shell]
script = '''
if [[ -d "$HOME"/Malcolm ]]; then
    echo "Shutting down and wiping Malcolm..."
    pushd "$HOME"/Malcolm
    python3 ./scripts/wipe \
        --verbose "$VERBOSE" || true
    popd
fi
'''